### ISSUE TITLE
Calculation of FPS is not accurate

### ISSUE THREAD

**Issue by hurali97** [bamlab/android-performance-profiler#17]
## Description:
After running this package with a release version of an app, I noticed that the FPS was always at 60. I downloaded the CSV from the generated web report and results in that CSV were also showing 60 FPS. So I debugged the calculation of FPS and I saw a comment:

<img width="692" alt="Screenshot 2022-08-30 at 7 47 20 PM" src="https://user-images.githubusercontent.com/47336142/187468331-2b79e047-ac76-467e-bd0b-14544eac1309.png">

But in my test cases automation is done to scroll the FlashList which means the list won't be idle and the FPS generation in such case seems faulty. I also tried to log the `frameTimes` and it had 2 items only once. In every consequent calculations this `frameTimes` array is empty. Which makes the `frameCount = 0` and we go to the assumption of FPS being 60, which is not precise.

## Test case:
```ts
import { AppiumDriver } from "@bam.tech/appium-helper";
import { TestCase, measurePerformance } from "@perf-profiler/e2e";

const bundleId = "com.some.id";

const getTestCases = async () => {
  const driver = await AppiumDriver.create({
    appPackage: bundleId,
    appActivity: `${bundleId}.MainActivity`,
  });

  const scrollTestCase: TestCase = {
    beforeTest: async () => {
      driver.stopApp();
      driver.startApp();
      await driver.clickElementByText("someButton1");
      await driver.clickElementByText("someButton2");
    },
    run: async () => {
      await driver.wait(2000)
      for (let index = 0; index < 5; index++) {
          await driver.scrollDown(2);
      }

      await driver.clickElementById("someButton3");
    },
  };

  return {
    SCROLL: scrollTestCase,
  };
};

test("e2e", async () => {
  const testCases = await getTestCases();

  const { writeResults } = await measurePerformance(
    bundleId,
    testCases.SCROLL,
    1
  );
  writeResults();
});
```

## Logs Output:

<details>
      
     console.log frameTimes  [ 50, 32.29 ]

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  2

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  54.12520000000001

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

     console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

     console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

      console.log frameTimes  []

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:45:11)
          at Array.forEach (<anonymous>)

      console.log frameCount  0

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:46:11)
          at Array.forEach (<anonymous>)

      console.log final FPS:  60

      at processOutput (../android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts:63:11)
          at Array.forEach (<anonymous>)

     console.log [19:13:46] ✅  Finished iteration 1/1 in 10028.164417028427ms

      at log (../logger/index.ts:25:11)
</details>

Now this 2 items concluding to 54 FPS is not present in the CSV and also not reflected on the web page report.

## CSV:
<img width="206" alt="Screenshot 2022-08-30 at 8 01 41 PM" src="https://user-images.githubusercontent.com/47336142/187471748-d0f068b9-4841-4da2-a671-8ffb7e5bcf17.png">

## Report:
<img width="1722" alt="Screenshot 2022-08-30 at 7 03 00 PM" src="https://user-images.githubusercontent.com/47336142/187472325-9645f717-307e-4e00-9858-e08d7170b1f1.png">

Let me know if I can help with anything else in explaining 🙂

**Comment by Almouro** [comment]
Hi @hurali97! 
Thanks for posting an issue here, you provided so many details and already debugged part of the issue it would seem, great skills! 🤩

So the first value is ignored because of https://github.com/bamlab/android-performance-profiler/blob/main/packages/android-performance-profiler/src/commands/pollPerformanceMeasures.ts#L32. It's a bit of an inaccuracy because CPU values need to be initialized first before we can check actual CPU usage. That could be fixed


However the biggest issue is that you're not receiving any frame times while scrolling down, which is definitely not supposed to happen 🤔
Could you try running 
```
adb shell /data/local/tmp/BAMPerfProfiler pollPerformanceMeasures $(adb shell pidof com.some.id) > measures.txt
``` 
while scrolling down manually  (replace `com.some.id` with your bundle id)

and send the measures over or just check if you see something like this: 
```
Profile data in ms:

        com.reactnativefeed/com.reactnativefeed.MainActivity/android.view.ViewRootImpl@77eac4c (visibility=0)
        Draw    Prepare Process Execute
        1.21    0.08    0.76    2.35
        1.23    0.08    5.42    1.90
        1.35    0.11    0.91    1.81
        3.14    0.32    1.35    2.74
        1.58    0.13    1.55    2.52
        1.55    0.10    0.85    1.79
        0.92    0.07    0.67    2.28
        1.06    0.07    0.61    2.41
        1.24    0.24    1.30    1.94
        1.20    0.08    1.54    2.45
        1.23    0.07    0.66    2.45
        1.34    0.26    2.28    2.15
        1.35    0.28    1.15    2.24
        1.19    0.09    1.94    2.17
        1.11    0.09    0.81    2.02
        1.70    0.10    0.78    1.97
        1.22    0.24    1.15    2.05
  ```

**Comment by hurali97** [comment]
Hi @Almouro

So I tried using the command, started scrolling and analysed the logs in the measures.txt file. But sadly I don't see any logs in that file. But then I logged the `gfxInfo` in `pollPerformanceMeasures` and I see these Draw, Prepare, Process and Execute stuff in the terminal. 

## Snapshot From Measures.txt
<img width="779" alt="Screenshot 2022-08-31 at 12 30 47 PM" src="https://user-images.githubusercontent.com/47336142/187619555-99e43ee0-97b7-409a-8d5d-758f1f5f50a0.png">


## Logs From `pollPerformanceMeasures`
<details>
    
    console.log
    gfxinfo  Applications Graphics Acceleration Info:
    Uptime: 562902 Realtime: 562902
    
    ** Graphics info for pid 6468 [com.some.id] **
    
    Stats since: 553814689722ns
    Total frames rendered: 367
    Janky frames: 243 (66.21%)
    50th percentile: 18ms
    90th percentile: 24ms
    95th percentile: 34ms
    99th percentile: 53ms
    Number Missed Vsync: 1
    Number High input latency: 230
    Number Slow UI thread: 10
    Number Slow bitmap uploads: 0
    Number Slow issue draw commands: 15
    Number Frame deadline missed: 20
    HISTOGRAM: 5ms=1 6ms=0 7ms=0 8ms=1 9ms=8 10ms=31 11ms=35 12ms=27 13ms=7 14ms=5 15ms=5 16ms=16 17ms=40 18ms=39 19ms=16 20ms=26 21ms=31 22ms=19 23ms=18 24ms=8 25ms=4 26ms=2 27ms=1 28ms=1 29ms=2 30ms=0 31ms=0 32ms=3 34ms=6 36ms=2 38ms=1 40ms=4 42ms=0 44ms=1 46ms=1 48ms=1 53ms=2 57ms=0 61ms=0 65ms=0 69ms=2 73ms=0 77ms=0 81ms=0 85ms=0 89ms=0 93ms=0 97ms=0 101ms=0 105ms=0 109ms=1 113ms=0 117ms=0 121ms=0 125ms=0 129ms=0 133ms=0 150ms=0 200ms=0 250ms=0 300ms=0 350ms=0 400ms=0 450ms=0 500ms=0 550ms=0 600ms=0 650ms=0 700ms=0 750ms=0 800ms=0 850ms=0 900ms=0 950ms=0 1000ms=0 1050ms=0 1100ms=0 1150ms=0 1200ms=0 1250ms=0 1300ms=0 1350ms=0 1400ms=0 1450ms=0 1500ms=0 1550ms=0 1600ms=0 1650ms=0 1700ms=0 1750ms=0 1800ms=0 1850ms=0 1900ms=0 1950ms=0 2000ms=0 2050ms=0 2100ms=0 2150ms=0 2200ms=0 2250ms=0 2300ms=0 2350ms=0 2400ms=0 2450ms=0 2500ms=0 2550ms=0 2600ms=0 2650ms=0 2700ms=0 2750ms=0 2800ms=0 2850ms=0 2900ms=0 2950ms=0 3000ms=0 3050ms=0 3100ms=0 3150ms=0 3200ms=0 3250ms=0 3300ms=0 3350ms=0 3400ms=0 3450ms=0 3500ms=0 3550ms=0 3600ms=0 3650ms=0 3700ms=0 3750ms=0 3800ms=0 3850ms=0 3900ms=0 3950ms=0 4000ms=0 4050ms=0 4100ms=0 4150ms=0 4200ms=0 4250ms=0 4300ms=0 4350ms=0 4400ms=0 4450ms=0 4500ms=0 4550ms=0 4600ms=0 4650ms=0 4700ms=0 4750ms=0 4800ms=0 4850ms=0 4900ms=0 4950ms=0
    50th gpu percentile: 2ms
    90th gpu percentile: 2ms
    95th gpu percentile: 2ms
    99th gpu percentile: 2ms
    GPU HISTOGRAM: 1ms=91 2ms=265 3ms=1 4ms=0 5ms=1 6ms=0 7ms=0 8ms=1 9ms=0 10ms=0 11ms=0 12ms=0 13ms=0 14ms=0 15ms=0 16ms=0 17ms=0 18ms=0 19ms=0 20ms=0 21ms=0 22ms=0 23ms=0 24ms=0 25ms=0 4950ms=0
    Font Cache (CPU):
      Size: 210.59 kB 
      Glyph Count: 43 
    CPU Caches:
      Shadows: 73.35 KB (7 entries)
    GPU Caches:
      Shadow Gaussian Falloff:
        Texture: 128.00 bytes (1 entry)
      Other:
        Other: 140.43 KB (1 entry)
        Buffer Object: 2.05 KB (2 entries)
      Image:
        Texture: 10.33 MB (43 entries)
      Scratch:
        RenderTarget: 11.55 MB (7 entries)
        Texture: 7.46 MB (329 entries)
        Buffer Object: 302.00 KB (9 entries)
    Other Caches:
                             Current / Maximum
      Layers Total           0.00 KB (numLayers = 0)
    Total GPU memory usage:
      31220244 bytes, 29.77 MB (9.94 MB is purgeable)
    
    
    Pipeline=Skia (OpenGL)
    Profile data in ms:
    
        com.some.id/com.some.id.MainActivity/android.view.ViewRootImpl@108da67 (visibility=8)
        Draw    Prepare Process Execute
    
        com.some.id/com.some.id.SomeReactActivity/android.view.ViewRootImpl@6fc0bfe (visibility=0)
        Draw    Prepare Process Execute
    
        com.some.id/com.some.id.SomeReactActivity/android.view.ViewRootImpl@93d2de2 (visibility=0)
        Draw    Prepare Process Execute
        2.59    0.18    6.83    1.76
        3.99    0.23    6.59    1.75
        3.91    0.23    6.33    1.33
        2.85    0.20    5.21    1.34
        2.82    0.19    6.83    1.52
        5.82    0.25    5.50    1.58
        3.60    0.22    6.63    1.57
        4.82    0.20    5.73    1.60
        4.12    0.20    5.36    1.48
        3.46    0.18    5.22    1.49
        3.25    0.20    5.08    1.53
        3.53    0.18    5.11    1.49
        3.36    0.18    5.05    1.54
        3.17    0.19    5.36    1.48
        3.94    0.18    5.08    1.48
        2.54    0.18    5.61    1.46
        2.61    0.18    5.32    1.43
        3.10    0.24    5.32    1.52
        4.55    0.26    6.11    1.60
        3.70    0.20    5.42    1.53
        3.67    0.18    5.75    1.54
        3.62    0.20    5.89    1.49
        3.74    0.18    5.43    1.42
        3.97    0.19    5.42    1.41
        3.47    0.18    5.50    1.58
        3.18    0.20    5.76    1.63
        2.22    0.21    5.61    1.50
        2.67    0.20    5.44    1.53
        2.35    0.21    5.67    1.59
        2.64    0.19    6.37    1.54
    
    View hierarchy:
    
      com.some.id/com.some.id.MainActivity/android.view.ViewRootImpl@108da67
      43 views, 49.94 kB of render nodes
    
      com.some.id/com.some.id.SomeReactActivity/android.view.ViewRootImpl@6fc0bfe
      506 views, 922.20 kB of render nodes
    
      com.some.id/com.some.id.SomeReactActivity/android.view.ViewRootImpl@93d2de2
      319 views, 587.21 kB of render nodes
    
    
    Total ViewRootImpl   : 3
    Total attached Views : 868
    Total RenderNode     : 1559.34 kB (used) / 5626.80 kB (capacity)

      at ../android-performance-profiler/src/commands/pollPerformanceMeasures.ts:51:17
          at Array.forEach (<anonymous>)
</details>

**Comment by Almouro** [comment]
Thanks for all the details @hurali97 !

Right, I see what the issue is, the frame times are on your 3rd window in the list, which is the one seemingly active, but the script takes the first one by default. Should be able to fix that soon!

**Comment by hurali97** [comment]
> Thanks for all the details @hurali97 !
> 
> Right, I see what the issue is, the frame times are on your 3rd window in the list, which is the one seemingly active, but the script takes the first one by default. Should be able to fix that soon!

Muchas gracias @Almouro  🚀

**Comment by Almouro** [comment]
Hi @hurali97, the last version should drastically improve accuracy of measures. The FPS measuring was completely overhauled and are retrieved via `atrace` now instead of `gfxinfo`

Let me know if that works for you!

**Comment by hurali97** [comment]
> Hi @hurali97, sorry that it took so long~ 🙏
> 
> But the last version should drastically improve accuracy of measures! 🥳 The FPS measuring was completely overhauled and are retrieved via `atrace` now instead of `gfxinfo`
> 
> Let me know if that works for you!

Hey @Almouro ,  I am so happy that you guys released a new version with more efficient calculations. Unfortunately, I am unable to test this issue due to certain blockers, nevertheless I will close it. And again, I appreciate your efforts for this tool, I am positive that I'll have some contributions in near future for this tool 🌟
