### ISSUE TITLE
Getting this error in the report generation

### ISSUE THREAD

**Issue by luckydunia054** [bamlab/android-performance-profiler#33]
hamri@hamris-MacBook-Pro techonomobileapp % npx ts-node performance.ts                  
[17:07:30] ℹ️  Installing C++ profiler for arm64-v8a architecture
[17:07:37] ✅  C++ Profiler installed in /data/local/tmp/BAMPerfProfiler
[17:07:46] ℹ️  Running iteration 1/10
args: [-p, com.techono, -c, android.intent.category.LAUNCHER, 1]
 arg: "-p"
 arg: "com.techono"
 arg: "-c"
 arg: "android.intent.category.LAUNCHER"
 arg: "1"
data="com.techono"
data="android.intent.category.LAUNCHER"
Error: Command failed: adb shell monkey -p com.techono -c android.intent.category.LAUNCHER 1
args: [-p, com.techono, -c, android.intent.category.LAUNCHER, 1]
 arg: "-p"
 arg: "com.techono"
 arg: "-c"
 arg: "android.intent.category.LAUNCHER"
 arg: "1"
data="com.techono"
data="android.intent.category.LAUNCHER"

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at startApp (/Users/hamri/Desktop/appproject/techonomobileapp/performance.ts:10:11)
    at run (/Users/hamri/Desktop/appproject/techonomobileapp/performance.ts:20:5)
    at PerformanceTester.<anonymous> (/Users/hamri/Desktop/appproject/techonomobileapp/node_modules/@perf-profiler/e2e/index.ts:31:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/hamri/Desktop/appproject/techonomobileapp/node_modules/@perf-profiler/e2e/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 252,
  signal: null,
  output: [
    null,
    Buffer(158) [Uint8Array] [
       32,  32,  98,  97, 115, 104,  32,  97, 114, 103,  58,  32,
       45, 112,  10,  32,  32,  98,  97, 115, 104,  32,  97, 114,
      103,  58,  32,  99, 111, 109,  46, 112, 114, 101, 112, 112,
       10,  32,  32,  98,  97, 115, 104,  32,  97, 114, 103,  58,
       32,  45,  99,  10,  32,  32,  98,  97, 115, 104,  32,  97,
      114, 103,  58,  32,  97, 110, 100, 114, 111, 105, 100,  46,
      105, 110, 116, 101, 110, 116,  46,  99,  97, 116, 101, 103,
      111, 114, 121,  46,  76,  65,  85,  78,  67,  72,  69,  82,
       10,  32,  32,  98,
      ... 58 more items
    ],
    Buffer(211) [Uint8Array] [
       97, 114, 103, 115,  58,  32,  91,  45, 112,  44,  32,  99,
      111, 109,  46, 112, 114, 101, 112, 112,  44,  32,  45,  99,
       44,  32,  97, 110, 100, 114, 111, 105, 100,  46, 105, 110,
      116, 101, 110, 116,  46,  99,  97, 116, 101, 103, 111, 114,
      121,  46,  76,  65,  85,  78,  67,  72,  69,  82,  44,  32,
       49,  93,  10,  32,  97, 114, 103,  58,  32,  34,  45, 112,
       34,  10,  32,  97, 114, 103,  58,  32,  34,  99, 111, 109,
       46, 112, 114, 101, 112, 112,  34,  10,  32,  97, 114, 103,
       58,  32,  34,  45,
      ... 111 more items
    ]
  ],
  pid: 14455,
  stdout: Buffer(158) [Uint8Array] [
     32,  32,  98,  97, 115, 104,  32,  97, 114, 103,  58,  32,
     45, 112,  10,  32,  32,  98,  97, 115, 104,  32,  97, 114,
    103,  58,  32,  99, 111, 109,  46, 112, 114, 101, 112, 112,
     10,  32,  32,  98,  97, 115, 104,  32,  97, 114, 103,  58,
     32,  45,  99,  10,  32,  32,  98,  97, 115, 104,  32,  97,
    114, 103,  58,  32,  97, 110, 100, 114, 111, 105, 100,  46,
    105, 110, 116, 101, 110, 116,  46,  99,  97, 116, 101, 103,
    111, 114, 121,  46,  76,  65,  85,  78,  67,  72,  69,  82,
     10,  32,  32,  98,
    ... 58 more items
  ],
  stderr: Buffer(211) [Uint8Array] [
     97, 114, 103, 115,  58,  32,  91,  45, 112,  44,  32,  99,
    111, 109,  46, 112, 114, 101, 112, 112,  44,  32,  45,  99,
     44,  32,  97, 110, 100, 114, 111, 105, 100,  46, 105, 110,
    116, 101, 110, 116,  46,  99,  97, 116, 101, 103, 111, 114,
    121,  46,  76,  65,  85,  78,  67,  72,  69,  82,  44,  32,
     49,  93,  10,  32,  97, 114, 103,  58,  32,  34,  45, 112,
     34,  10,  32,  97, 114, 103,  58,  32,  34,  99, 111, 109,
     46, 112, 114, 101, 112, 112,  34,  10,  32,  97, 114, 103,
     58,  32,  34,  45,
    ... 111 more items
  ]
}
hamri@hamris-MacBook-Pro techonomobileapp % npx @perf-profiler/web-reporter results.json
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'results.json'
    at Object.lstatSync (node:fs:1529:3)
    at /Users/hamri/.npm/_npx/236afad33dc9fea1/node_modules/@perf-profiler/web-reporter/dist/writeReport.js:20:46
    at Array.map (<anonymous>)
    at getJsonPaths (/Users/hamri/.npm/_npx/236afad33dc9fea1/node_modules/@perf-profiler/web-reporter/dist/writeReport.js:19:14)
    at writeReport (/Users/hamri/.npm/_npx/236afad33dc9fea1/node_modules/@perf-profiler/web-reporter/dist/writeReport.js:33:35)
    at Object.<anonymous> (/Users/hamri/.npm/_npx/236afad33dc9fea1/node_modules/@perf-profiler/web-reporter/dist/openReport.js:16:52)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'results.json'
}
hamri@hamris-MacBook-Pro techonomobileapp % 

I tried with npx ts-node performance.ts method but it is not working also tried with another methods but nothing worked so let me know what is error over here and how can i connect it with production

**Comment by Almouro** [comment]
Hi @luckydunia054, thanks for the issue and for trying to get it to work!

It would seem the plugin even failed to start your app quite surprisingly since I see the command starting the app erroring in your logs
```
Error: Command failed: adb shell monkey -p com.techono -c android.intent.category.LAUNCHER 1
```

What do you get if you run this command alone from a terminal? `adb shell monkey -p com.techono -c android.intent.category.LAUNCHER 1`

**Comment by Almouro** [comment]
Hi @luckydunia054, I'm closing this one for lack of response, but feel free to reopen/mention if this is still an issue!
