### ISSUE TITLE
Couldn't launch the script on old android

### ISSUE THREAD

**Issue by charlotteisambert** [bamlab/android-performance-profiler#48]
When I ran my appium script (npx ts-node tf1-info.ts), I got this error: 

```
/Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/atrace/pollFpsUsage.ts:48
    lines.forEach((line) => {
          ^
TypeError: Cannot read property 'includes' of undefined
    at /Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/atrace/pollFpsUsage.ts:64:24
    at Array.forEach (<anonymous>)
    at FrameTimeParser.getFrameTimes (/Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/atrace/pollFpsUsage.ts:48:11)
    at /Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/pollPerformanceMeasures.ts:26:25
    at /Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/cppProfiler.ts:104:7
    at /Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/shell.ts:49:7
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/Users/charlotte/Documents/Projects/node_modules/@perf-profiler/profiler/src/commands/shell.ts:48:29)
    at Socket.emit (node:events:365:28)
    at Socket.emit (node:domain:470:12)`

```

The script had just printed `Running iteration 1/10`

Here is my script: 
```
import { AppiumDriver } from "@bam.tech/appium-helper";
import { TestCase, measurePerformance } from "@perf-profiler/e2e";

const runTest = async () => {
  const driver = await AppiumDriver.create({
    // `npx @perf-profiler/profiler getCurrentApp` will display info for the current app
    appPackage: "com.smartnsoft.metro",
    appActivity: "com.mobilenews.MainActivity",
  });

  const testCase: TestCase = {
    beforeTest: async () => {
      driver.stopApp();
    },
    run: async () => {
      // run is where measuring will happen, insert e2e logic here
      driver.startApp();
      await driver.findElementByText("Bonjour");
    },
    // Duration is optional, but helps in getting consistent measures.
    // Measures will be taken for this duration, regardless of test duration
    duration: 10000,
  };

  const { writeResults } = await measurePerformance("com.smartnsoft.metro", testCase);
  writeResults();
};

runTest()
```

Android phone: Samsung A30
Android version: 10

FYI, it is the same script that I launched on another phone (pixel 6, android 13) where it worked

**Comment by Almouro** [comment]
Should be fixed in `@perf-profiler/e2e@0.5.3`! 🎈
